Test_WebApi/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.SignalR;
using Test_WebApi;
using Test_WebApi.Hubs;
using Test_WebApi.Models;
using WebGrease.ImageAssemble;

namespace Test_WebApi.Controllers
{
    public class InventoryController : Controller
    {
        private static readonly IHubContext Context = GlobalHost.ConnectionManager.GetHubContext<InventoryHub>();

        // GET: Inventory
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetInventory()
        {
            using (var db = new SignalRContext())
            {
                return Json(await db.IntentoryItems.Select(u => new { u.ID, u.Name, u.Quantity, u.Price }).ToListAsync(), JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Inventory/Details/5
        [System.Web.Mvc.Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var db = new SignalRContext())
            {
                InventoryItem inventoryItem = await db.IntentoryItems.Include(i => i.User).SingleOrDefaultAsync(s => s.ID == id);
                if (inventoryItem == null)
                {
                    return HttpNotFound();
                }
                return View(inventoryItem);
            }
        }

        // GET: Inventory/Create
        [System.Web.Mvc.Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [System.Web.Mvc.Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,UserID,Name,Quantity,Price")] InventoryItem inventoryItem)
        {
            if (!ModelState.IsValid) return View(inventoryItem);
            using (var db = new SignalRContext())
            {
                inventoryItem.User =
                    await db.Users.FirstOrDefaultAsync(u => u.UserName == System.Web.HttpContext.Current.User.Identity.Name);
                db.IntentoryItems.Add(inventoryItem);
                await db.SaveChangesAsync();
                Context.Clients.All.addOrUpdate(new
                {
                    ID = inventoryItem.ID,
                    Name = inventoryItem.Name,
                    Quantity = inventoryItem.Quantity,
                    Price = inventoryItem.Price
                });
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Inventory/Edit/5
        [System.Web.Mvc.Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new SignalRContext())
            {
                InventoryItem inventoryItem = await db.IntentoryItems.Include(i => i.User).SingleOrDefaultAsync(s => s.ID == id);
                if (inventoryItem == null)
                {
                    return HttpNotFound();
                }
                return View(inventoryItem);
            }
        }

        // POST: Inventory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [System.Web.Mvc.Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,UserID,Name,Quantity,Price")] InventoryItem inventoryItem)
        {
            if (!ModelState.IsValid) return View(inventoryItem);
            using (var db = new SignalRContext())
            {
                db.Entry(inventoryItem).State = EntityState.Modified;
                await db.SaveChangesAsync();
                Context.Clients.All.addOrUpdate(new
                {
                    ID = inventoryItem.ID,
                    Name = inventoryItem.Name,
                    Quantity = inventoryItem.Quantity,
                    Price = inventoryItem.Price
                });
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Inventory/Delete/5
        [System.Web.Mvc.Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var db = new SignalRContext())
            {
                InventoryItem inventoryItem = await db.IntentoryItems.FindAsync(id);
                if (inventoryItem == null)
                {
                    return HttpNotFound();
                }
                return View(inventoryItem);
            }
        }

        // POST: Inventory/Delete/5
        [System.Web.Mvc.Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            using (var db = new SignalRContext())
            {
                InventoryItem inventoryItem = await db.IntentoryItems.FindAsync(id);
                db.IntentoryItems.Remove(inventoryItem);
                await db.SaveChangesAsync();
                Context.Clients.All.remove(new { ID = inventoryItem.ID });
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Test_WebApi/Views/Inventory/Create.cshtml
@model Test_WebApi.Models.InventoryItem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inventory Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","Inventory")" role="button" class="btn btn-primary">Back to list <span class="glyphicon glyphicon-list"></span></a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Test_WebApi/Views/Inventory/Delete.cshtml
@model Test_WebApi.Models.InventoryItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory Item</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a href="@Url.Action("Index","Inventory")" role="button" class="btn btn-primary">Back to list <span class="glyphicon glyphicon-list"></span></a>
        </div>
    }
</div>

Test_WebApi/Views/Inventory/Details.cshtml
@model Test_WebApi.Models.InventoryItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Inventory Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Created by:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit","Inventory", new {id=Model.ID})" role="button" class="btn-sm btn-warning">Edit <span class="glyphicon glyphicon-pencil"></span></a> |
    <a href="@Url.Action("Index","Inventory")" role="button" class="btn btn-primary">Back to list <span class="glyphicon glyphicon-list"></span></a>
</p>

Test_WebApi/Views/Inventory/Edit.cshtml
@model Test_WebApi.Models.InventoryItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inventory Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.UserID)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","Inventory")" role="button" class="btn btn-primary">Back to list <span class="glyphicon glyphicon-list"></span></a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Test_WebApi/Views/Inventory/Index.cshtml
@model Test_WebApi.Models.InventoryItem
@{
    ViewBag.Title = "Inventory";
}

<div class="jumbotron">
    <h1>Inventory</h1>
    <br />
    @if (System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
    {
        <p>
            <a href="@Url.Action("Create", "Inventory")" role="button" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> New Inventory Item</a>
        </p>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Price
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody data-bind="foreach: inventory">
            <tr>
                <td>
                    <input type="hidden" data-bind="value: ID" /><span data-bind="text: Name"></span>
                </td>
                <td><span data-bind="text: Quantity"></span></td>
                <td><span data-bind="text: Price"></span></td>
                @if (System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <td class="text-right">
                        <button onclick="ViewDetails(this);" class="btn-sm btn-primary">Details <span class="glyphicon glyphicon-search"></span></button>
                        <button onclick="Edit(this);" class="btn-sm btn-warning">Edit <span class="glyphicon glyphicon-pencil"></span></button>
                        <button onclick="Delete(this);" class="btn-sm btn-danger">Delete <span class="glyphicon glyphicon-trash"></span></button>
                    </td>
                }
            </tr>
        </tbody>
    </table>
</div>
@section scripts{
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/knockout.js"></script>
    <script src="~/Scripts/CustomScripts/customInventory.js"></script>
}